### ISSUE TITLE
Cannot Create EPUB file, problem with decoding

### ISSUE THREAD

**Issue by flxlocle** [lorenzodifuccia/safaribooks#172]
I ran the program and it gave me this output:
![ERORR](https://user-images.githubusercontent.com/53885793/71634975-5f577780-2bee-11ea-9fd2-4dd39a622b3f.PNG)
Please help, thank you.

**Comment by TheSnoozer** [comment]
There seems to be two issues:
1) the first one (why the process fails) is just below the message of creating an EPUB `Unhandled Exception: 'NoneType' object has no attribute 'replace' (type: AttributeError)` and I believe this could be related to https://github.com/lorenzodifuccia/safaribooks/issues/171. Essentially the issue is that the EPUB creation process fails when a book does not have a description. Could you try to search for `escape(self.book_info["description"])` and replace it with `escape(self.book_info["description"] or "")`?
2) Seems to be a windows encoding issue. As far as i can recall windows uses `cp1252` as default encoding. You should be able to change this by executing `chcp 65001` just before running the book download. See also https://stackoverflow.com/a/42070962/7890667
