### ISSUE TITLE
Trying to download an existing book duplicates the file size

### ISSUE THREAD

**Issue by diegorodriguezv** [lorenzodifuccia/safaribooks#205]
For example, run:
`python3 safaribooks.py 9781491958698`
list the file:
`7336044 Apr 17 13:05 9781491958698.epub`
run it again:
`python3 safaribooks.py 9781491958698`
(It warns that File `default_cover.jpeg` already exists. but "creates" the file again: Creating EPUB file...)
list the file:
`14680548 Apr 19 01:18 9781491958698.epub`
do it again and the file size triples:
`22027412 Apr 19 01:30 9781491958698.epub`
Actually doing the math the second run adds 8460 bytes (past double) and the third run 10820 bytes.
If you open the epub file as a zip it contains the past epub file (which in turn contains the past one).

I would expect the warning telling me that the files have already been downloaded but not the doubling of the file size.
Thanks in advance for your help.

**Comment by lorenzodifuccia** [comment]
Hello @diegorodriguezv,
the problem here is that the structure of the program, where images are collected by parsing the HTML of pages one by one, implies that we cannot resume an old process.
I realised the script with this assumption in mind and so, if you run the program twice, you will trigger the error "File `foo` already exists. If you want to download again all the images, please delete the output directory...".
The solution is to delete the directory before re-download the same book.
Maybe future development of the code will fix this problem...

**Comment by diegorodriguezv** [comment]
I'll take a look at it.
