### ISSUE TITLE
Non è legale

### ISSUE THREAD

**Issue by dzonerzy** [lorenzodifuccia/safaribooks#27]
Ciò che hai sviluppato non è legale

**Comment by lorenzodifuccia** [comment]
English translation of the issue: "It's illegal. What you developed it's illegal."

Hi @dzonerzy, what I developed it not illegal and I'll show you why:
- I'm merely offering a script that download and convert `.html` pages into a `.epub` archive. That's it!
- I'm not distributing O'Reilly credentials nor O'Reilly contents.
- Any O'Reilly authorization or encryption mechanisms are untouched.
- I'm not breaking any laws, copyrights nor term of services (TOS) because what the script does is to access and download `.html` pages from Safari Books using the *user* provided O'Reilly credentials. It's like the offline copy feature of the book available in the Android/iOS O'Reilly official mobile application.
- As the banner says: "I'm not responsible for the use of this program, this is only for personal and educational purpose". I wrote this script for educational purpose, what the people do with my program it's related to them. *Who made the gun is responsible for the kills done?*
- If an user downloads a book from Safari using my script, he's providing and using his credentials, not mine. So, he will be responsible for the download and for all future actions. **It's demanded to the user to respect the O'Reilly's TOS, like never distribute nor keep copy of the book if the license is expired**.

Hoping that I accomplished to answer your question.
Thanks for the clarification.
Lorenzo
