### ISSUE TITLE
SSO stopped working... 

### ISSUE THREAD

**Issue by dwightmulcahy** [lorenzodifuccia/safaribooks#273]
I now get this after I copied my cookies from the profile page... 

is it broke again?

```
 ██████╗     ██████╗ ██╗  ██╗   ██╗██████╗ 
██╔═══██╗    ██╔══██╗██║  ╚██╗ ██╔╝╚════██╗
██║   ██║    ██████╔╝██║   ╚████╔╝   ▄███╔╝
██║   ██║    ██╔══██╗██║    ╚██╔╝    ▀▀══╝ 
╚██████╔╝    ██║  ██║███████╗██║     ██╗   
 ╚═════╝     ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝                                           

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[#] Authentication issue: unable to access profile page.
[!] Aborting...
```

**Comment by fullstackzach** [comment]
Same here

**Comment by regulskimichal** [comment]
Does --cred method work for you?

**Comment by fullstackzach** [comment]
Since I am using SSO - I do not have a password to use since I'm authenticated through my organization.
It looks like `--cred` expects an email and a password to be supplied. I tried using email only and that did not work; 

usage: safaribooks.py [--cred <EMAIL:PASS> | --login] [--no-cookies]
                      [--kindle] [--preserve-log] [--help]
                      <BOOK ID>
safaribooks.py: error: invalid credential:  <email>

**Comment by rustypangolin** [comment]
Same here (ACM). Seems like they've changed the auth scheme, the session ID is significantly longer than it used to, groot_sessionid is also missing,

**Comment by aaronkyl** [comment]
Make sure you update to the latest version of the script. I haven't updated in a few months and was having the same issue, but one quick `git pull origin master` and it's working again!
