### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by ashokrai** [lorenzodifuccia/safaribooks#74]
In windows 10, when I run the command
D:\safaribooks>python safaribooks.py --cred "myemail:mypassword" bookisbn 
the following error occurs;

Error in sys.excepthook:
Traceback (most recent call last):
  File "safaribooks.py", line 98, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "safaribooks.py", line 84, in exit
    self.error(str(error))
  File "safaribooks.py", line 81, in error
    self.out(output)
  File "safaribooks.py", line 67, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + put.encode("utf-8", "replace") + "\n")
TypeError: can only concatenate str (not "bytes") to str

Original exception was:
Traceback (most recent call last):
  File "safaribooks.py", line 1026, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 274, in __init__
    self.display.intro()
  File "safaribooks.py", line 117, in intro
    self.out(output)
  File "safaribooks.py", line 67, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + put.encode("utf-8", "replace") + "\n")
TypeError: can only concatenate str (not "bytes") to str

**Comment by fgsummer** [comment]
Because of  401:
[#] API: Out-of-Session (Authentication credentials were not provided.). 

cookies:{'BrowserCookie': '1481717c-9e93-4ef8-...1ea54b723', 'csrfsafari': 'wqOUcWBE9xxhFPqHR1F...7m8Fba3CM', 'sessionid': '0cddpq1y7dbesga8vkw...pyw8s57m7'}
'BrowserCookie' (4406206320):'1481717c-9e93-4ef8-b491-9e31ea54b723'
'csrfsafari' (4406206000):'wqOUcWBE9xxhFPqHR1FJRXq12rmPEqh3PE7G8hHAS0f3VNuEdoYF32V7m8Fba3CM'
'sessionid' (4406205616):'0cddpq1y7dbesga8vkw5d4xpyw8s57m7'
__len__:3

Works with cookie.json

https://github.com/lorenzodifuccia/safaribooks/issues/2

**Comment by lorenzodifuccia** [comment]
e4c8c55 should fix this issue.

**Comment by lorenzodifuccia** [comment]
Pull last commit: b96819b

**Comment by ashokrai** [comment]
Thank you, indeed, this solved the problem.
